Repository boostcampwm-2022/iOS03-DailyQuest, pull requests merged in 2022-11, with the labels that each got.

#7 UserInfoCell 구현
  DailyQuest/DailyQuest.xcodeproj/project.pbxproj
  DailyQuest/DailyQuest/Assets.xcassets/LightGray.colorset/Contents.json
  DailyQuest/DailyQuest/Domain/Entities/Quest.swift
  DailyQuest/DailyQuest/Presentation/Common/UserInfoCell.swift
Labels: 리뷰요청, 진웅, feature

#8 CalendarCell 구현
  DailyQuest/DailyQuest.xcodeproj/project.pbxproj
  DailyQuest/DailyQuest/Presentation/Common/CalendarCellCollectionViewCell.swift
  DailyQuest/DailyQuest/Presentation/Common/CircleCheckView.swift
Labels: 리뷰요청, 동훈, feature

#9 QuestView와 QuestCell 완성
  DailyQuest/DailyQuest.xcodeproj/project.pbxproj
  DailyQuest/DailyQuest/Presentation/Common/QuestCell.swift
  DailyQuest/DailyQuest/Presentation/Common/QuestView.swift
Labels: 리뷰요청, 다연, feature

#15 Browse cell 일부 구현
  DailyQuest/DailyQuest.xcodeproj/project.pbxproj
  DailyQuest/DailyQuest/Application/SceneDelegate.swift
  DailyQuest/DailyQuest/Presentation/Browse/View/BrowseViewController.swift
  DailyQuest/DailyQuest/Presentation/Browse/ViewModel/BrowseItemViewModel.swift
  DailyQuest/DailyQuest/Presentation/Browse/ViewModel/BrowseViewModel.swift
  DailyQuest/DailyQuest/Presentation/Common/Cells/BrowseCell.swift
  DailyQuest/DailyQuest/Presentation/Common/Cells/QuestCell.swift
  DailyQuest/DailyQuest/Presentation/Common/CustomProgressBar.swift
  DailyQuest/DailyQuest/Presentation/Common/QuestView.swift
Labels: 리뷰요청, 진웅, feature

#13 Feature/realm
  DailyQuest/DailyQuest.xcodeproj/project.pbxproj
  DailyQuest/DailyQuest/Data/PersistentStorages/BrowseQuest.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/BrowseQuestsStorage/BrowseQuestsStorage.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/BrowseQuestsStorage/RealmStorage/EntityMapping/BrowseQuestEntity+Mapping.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/BrowseQuestsStorage/RealmStorage/RealmBrowseQuestsStorage.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/RealmStorage/Entities/BrowseQuestEntity.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/RealmStorage/Entities/UserInfoEntity.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/RealmStorage/Entities/UserQuestEntity.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/RealmStorage/RealmStorage.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/UserInfoStorage/RealmStorage/EntityMapping/UserInfoEntity+Mapping.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/UserInfoStorage/RealmStorage/RealmUserInfoStorage.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/UserInfoStorage/UserInfoStorage.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/UserQuestsStorage/RealmStorage/EntityMapping/UserQuestEntity+Mapping.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/UserQuestsStorage/RealmStorage/RealmUserQuestsStorage.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/UserQuestsStorage/UserQuestsStorage.swift
  DailyQuest/DailyQuest/Domain/Entities/Quest.swift
Labels: 리뷰요청, 전희, feature

#20 Cell Identifier를 올바르게 수정
  DailyQuest/DailyQuest/Presentation/Common/Cells/BrowseCell.swift
  DailyQuest/DailyQuest/Presentation/Common/Cells/QuestCell.swift
Labels: 진웅, refactor

#22 TabBarPage 메서드 수정
  DailyQuest/DailyQuest/Application/AppCoordinator.swift
  DailyQuest/DailyQuest/Application/Protocols/TabCoordinator.swift
Labels: 진웅, refactor

#23 BrowseView 구성
  DailyQuest/DailyQuest.xcodeproj/project.pbxproj
  DailyQuest/DailyQuest/Application/AppAppearance.swift
  DailyQuest/DailyQuest/Presentation/Browse/View/UserInfoView.swift
  DailyQuest/DailyQuest/Presentation/Browse/ViewController/BrowseViewController.swift
  DailyQuest/DailyQuest/Presentation/Browse/ViewModel/BrowseViewModel.swift
  DailyQuest/DailyQuest/Presentation/Common/Cells/BrowseCell.swift
Labels: 리뷰요청, 진웅, feature

#25 QuestView 작성, 버튼 클릭시, AddQuestsView present
  DailyQuest/DailyQuest.xcodeproj/project.pbxproj
  DailyQuest/DailyQuest/Presentation/Home/Flow/HomeCoordinator.swift
  DailyQuest/DailyQuest/Presentation/Home/View/QuestView.swift
  DailyQuest/DailyQuest/Presentation/Home/View/QuestViewHeader.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewController/AddQuestsViewController.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewController/HomeViewController.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewModel/QuestViewModel.swift
  DailyQuest/DailyQuest/Utils/UIButton+.swift
Labels: 리뷰요청, 진웅, feature

#30 QuestUseCase 작성 및 테스트
  DailyQuest/DailyQuest.xcodeproj/project.pbxproj
  DailyQuest/DailyQuest/Data/PersistentStorages/UserQuestsStorage/RealmStorage/EntityMapping/UserQuestEntity+Mapping.swift
  DailyQuest/DailyQuest/Domain/Entities/Quest.swift
  DailyQuest/DailyQuest/Domain/Interfaces/Repositories/QuestsRepository.swift
  DailyQuest/DailyQuest/Domain/UseCases/Home/DefaultQuestUseCase.swift
  DailyQuest/DailyQuest/Domain/UseCases/Home/Protocols/QuestUseCase.swift
  DailyQuest/DailyQuest/Presentation/Browse/ViewModel/BrowseViewModel.swift
  DailyQuest/DailyQuest/Presentation/Common/Cells/QuestCell.swift
  DailyQuest/DailyQuest/Presentation/Home/View/QuestView.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewController/HomeViewController.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewModel/QuestViewModel.swift
  DailyQuest/DailyQuestTests/DailyQuestTests.swift
  DailyQuest/DailyQuestTests/Domain/UseCases/Mocks/QuestRepositoryMock.swift
  DailyQuest/DailyQuestTests/Domain/UseCases/QuestUseCaseTests.swift
  DailyQuest/DailyQuestTests/Mocks/Quest+Stub.swift
Labels: 리뷰요청, 진웅, feature

#34 Feature/quest repository
  DailyQuest/DailyQuest.xcodeproj/project.pbxproj
  DailyQuest/DailyQuest/Application/SceneDelegate.swift
  DailyQuest/DailyQuest/Data/Network/DataMapping/DTO.swift
  DailyQuest/DailyQuest/Data/Network/DataMapping/QuestDTO+Mapping.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/BrowseQuestsStorage/RealmStorage/EntityMapping/BrowseQuestEntity+Mapping.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/BrowseQuestsStorage/RealmStorage/RealmBrowseQuestsStorage.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/QuestsStorage/QuestsStorage.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/QuestsStorage/RealmStorage/EntityMapping/QuestEntity+Mapping.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/QuestsStorage/RealmStorage/RealmQuestsStorage.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/RealmStorage/Entities/BrowseQuestEntity.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/RealmStorage/Entities/QuestEntity.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/RealmStorage/RealmStorage.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/UserInfoStorage/RealmStorage/RealmUserInfoStorage.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/UserQuestsStorage/RealmStorage/EntityMapping/UserQuestEntity+Mapping.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/UserQuestsStorage/RealmStorage/RealmUserQuestsStorage.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/UserQuestsStorage/UserQuestsStorage.swift
  DailyQuest/DailyQuest/Data/Repositories/DefaultQuestsRepository.swift
  DailyQuest/DailyQuest/Domain/Entities/Quest.swift
  DailyQuest/DailyQuest/Infrastructure/FirebaseService/FirebaseService.swift
  DailyQuest/DailyQuest/Infrastructure/NetworkConfigure.swift
  DailyQuest/DailyQuest/Infrastructure/NetworkService.swift
  DailyQuest/DailyQuest/Presentation/Browse/ViewModel/BrowseViewModel.swift
  DailyQuest/DailyQuest/Presentation/Common/Cells/QuestCell.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewModel/QuestViewModel.swift
  DailyQuest/DailyQuest/Utils/Date+.swift
  DailyQuest/DailyQuest/Utils/String+.swift
Labels: 리뷰요청, 전희, feature

#38 Feature/launchingview PR
  DailyQuest/DailyQuest.xcodeproj/project.pbxproj
  DailyQuest/DailyQuest.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DailyQuest/DailyQuest/Base.lproj/LaunchScreen.storyboard
  DailyQuest/DailyQuest/Presentation/Home/ViewController/HomeViewController.swift
  DailyQuest/DailyQuest/max-loading.json
Labels: 리뷰요청, 다연, feature

#42 Feature/quest view model
  DailyQuest/DailyQuest.xcodeproj/project.pbxproj
  DailyQuest/DailyQuest.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DailyQuest/DailyQuest/Presentation/Home/View/QuestView.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewModel/QuestViewModel.swift
  DailyQuest/DailyQuestTests/Domain/Mocks/QuestRepositoryMock.swift
  DailyQuest/DailyQuestTests/Presentation/Mocks/QuestUseCaseMock.swift
  DailyQuest/DailyQuestTests/Presentation/ViewModel/QuestViewModelTests.swift
Labels: 리뷰요청, 진웅, feature

#48 Feature/connect quest layer
  DailyQuest/DailyQuest/Application/DIContainer/HomeSceneDIContainer.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewController/HomeViewController.swift
Labels: 리뷰요청, 진웅, feature

#50 Feature/settings view
  DailyQuest/DailyQuest.xcodeproj/project.pbxproj
  DailyQuest/DailyQuest/Application/AppAppearance.swift
  DailyQuest/DailyQuest/Application/AppCoordinator.swift
  DailyQuest/DailyQuest/Application/DIContainer/AppDIContainer.swift
  DailyQuest/DailyQuest/Application/DIContainer/SettingsSceneDIContainer.swift
  DailyQuest/DailyQuest/Presentation/Home/View/StatusView.swift
  DailyQuest/DailyQuest/Presentation/Settings/Flow/SettingsCoordinator.swift
  DailyQuest/DailyQuest/Presentation/Settings/View/CommonField.swift
  DailyQuest/DailyQuest/Presentation/Settings/View/NavigateField/NavigateCell.swift
  DailyQuest/DailyQuest/Presentation/Settings/View/NavigateField/NavigateField.swift
  DailyQuest/DailyQuest/Presentation/Settings/View/NavigateField/NavigateItemViewModel.swift
  DailyQuest/DailyQuest/Presentation/Settings/View/PlainField/PlainCell.swift
  DailyQuest/DailyQuest/Presentation/Settings/View/PlainField/PlainField.swift
  DailyQuest/DailyQuest/Presentation/Settings/View/PlainField/PlainItemViewModel.swift
  DailyQuest/DailyQuest/Presentation/Settings/View/ToggleField/ToggleCell.swift
  DailyQuest/DailyQuest/Presentation/Settings/View/ToggleField/ToggleField.swift
  DailyQuest/DailyQuest/Presentation/Settings/View/ToggleField/ToggleItemViewModel.swift
  DailyQuest/DailyQuest/Presentation/Settings/ViewController/SettingsViewController.swift
Labels: 리뷰요청, 진웅, feature

#52 Feature/firebase
  DailyQuest/DailyQuest.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DailyQuest/DailyQuest/Data/Network/DataMapping/QuestDTO+Mapping.swift
  DailyQuest/DailyQuest/Infrastructure/FirebaseService/FirebaseService.swift
  DailyQuest/DailyQuest/Infrastructure/NetworkConfigure.swift
  DailyQuest/DailyQuest/Infrastructure/NetworkService.swift
  DailyQuest/DailyQuestTests/Domain/Mocks/QuestRepositoryMock.swift
  DailyQuest/DailyQuestTests/Mocks/Quest+Stub.swift
Labels: 리뷰요청, 전희, 다연

#55 Login view, viewmodel, usecase
  DailyQuest/DailyQuest.xcodeproj/project.pbxproj
  DailyQuest/DailyQuest/Domain/UseCases/Home/DefaultAuthUseCase.swift
  DailyQuest/DailyQuest/Domain/UseCases/Home/Protocols/AuthUseCase.swift
  DailyQuest/DailyQuest/Presentation/Common/TextFieldForm.swift
  DailyQuest/DailyQuest/Presentation/Settings/Flow/SettingsCoordinator.swift
  DailyQuest/DailyQuest/Presentation/Settings/View/CommonField.swift
  DailyQuest/DailyQuest/Presentation/Settings/View/NavigateField/NavigateField.swift
  DailyQuest/DailyQuest/Presentation/Settings/View/NavigateField/NavigateItemViewModel.swift
  DailyQuest/DailyQuest/Presentation/Settings/ViewController/LoginViewController.swift
  DailyQuest/DailyQuest/Presentation/Settings/ViewController/SettingsViewController.swift
  DailyQuest/DailyQuest/Presentation/Settings/ViewModel/AuthViewModel.swift
Labels: 리뷰요청, 진웅, feature

#58 Feature/connect login layer
  DailyQuest/DailyQuest.xcodeproj/project.pbxproj
  DailyQuest/DailyQuest/Application/DIContainer/SettingsSceneDIContainer.swift
  DailyQuest/DailyQuest/Presentation/Settings/Flow/SettingsCoordinator.swift
  DailyQuest/DailyQuest/Presentation/Settings/ViewController/LoginViewController.swift
  DailyQuest/DailyQuest/Presentation/Settings/ViewModel/LoginViewModel.swift
Labels: 리뷰요청, 진웅, feature

#63 Feature/browse use case, viewModel
  DailyQuest/DailyQuest.xcodeproj/project.pbxproj
  DailyQuest/DailyQuest/Application/DIContainer/BrowseSceneDIContainer.swift
  DailyQuest/DailyQuest/Domain/UseCases/Browse/DefaultBrowseUseCase.swift
  DailyQuest/DailyQuest/Domain/UseCases/Browse/Protocols/BrowseUseCase.swift
  DailyQuest/DailyQuest/Domain/UseCases/DefaultAuthUseCase.swift
  DailyQuest/DailyQuest/Domain/UseCases/Settings/Protocols/AuthUseCase.swift
  DailyQuest/DailyQuest/Presentation/Browse/ViewController/BrowseViewController.swift
  DailyQuest/DailyQuest/Presentation/Browse/ViewModel/BrowseViewModel.swift
  DailyQuest/DailyQuestTests/Domain/Mocks/BrowseRepositoryMock.swift
  DailyQuest/DailyQuestTests/Domain/UseCases/BrowseUseCaseTests.swift
  DailyQuest/DailyQuestTests/Mocks/BrowseQuest+Stub.swift
  DailyQuest/DailyQuestTests/Mocks/User+Stub.swift
  DailyQuest/DailyQuestTests/Presentation/Mocks/BrowseUseCaseMock.swift
  DailyQuest/DailyQuestTests/Presentation/Mocks/QuestUseCaseMock.swift
  DailyQuest/DailyQuestTests/Presentation/ViewModel/BrowseViewModelTests.swift
Labels: 진웅, feature

#65 Refactor/firebase
  DailyQuest/DailyQuest/Infrastructure/FirebaseService/FirebaseService.swift
  DailyQuest/DailyQuest/Infrastructure/NetworkConfigure.swift
  DailyQuest/DailyQuest/Infrastructure/NetworkService.swift
Labels: 리뷰요청, 전희, refactor
