Repository boostcampwm-2022/iOS03-DailyQuest, pull requests merged in 2022-12, with the labels that each got.

#68 Feature/enroll view
  DailyQuest/DailyQuest.xcodeproj/project.pbxproj
  DailyQuest/DailyQuest/Domain/UseCases/Settings/DefaultAuthUseCase.swift
  DailyQuest/DailyQuest/Presentation/Common/TextFieldForm.swift
  DailyQuest/DailyQuest/Presentation/Home/Flow/HomeCoordinator.swift
  DailyQuest/DailyQuest/Presentation/Home/View/DayNamePickerView.swift
  DailyQuest/DailyQuest/Presentation/Home/View/PlanDatePickerView.swift
  DailyQuest/DailyQuest/Presentation/Home/View/QuantityView.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewController/AddQuestsViewController.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewController/EnrollViewController.swift
Labels: 리뷰요청, 진웅, feature

#70 Feature/quest view cell actions
  DailyQuest/DailyQuest/Domain/Entities/Quest.swift
  DailyQuest/DailyQuest/Domain/UseCases/Home/DefaultQuestUseCase.swift
  DailyQuest/DailyQuest/Domain/UseCases/Home/Protocols/QuestUseCase.swift
  DailyQuest/DailyQuest/Presentation/Home/View/QuestView.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewController/HomeViewController.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewModel/QuestViewModel.swift
Labels: 진웅, feature

#72 Feature/following view
  DailyQuest/DailyQuest.xcodeproj/project.pbxproj
  DailyQuest/DailyQuest/Presentation/Home/View/FollowingCell.swift
  DailyQuest/DailyQuest/Presentation/Home/View/FollowingView.swift
  DailyQuest/DailyQuest/Presentation/Home/View/LastFollowingCell.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewController/HomeViewController.swift
Labels: 리뷰요청, 다연, feature

#79 Feature/enroll view model
  DailyQuest/DailyQuest.xcodeproj/project.pbxproj
  DailyQuest/DailyQuest/Application/DIContainer/HomeSceneDIContainer.swift
  DailyQuest/DailyQuest/Domain/UseCases/Home/DefaultEnrollUseCase.swift
  DailyQuest/DailyQuest/Domain/UseCases/Home/Protocols/EnrollUseCase.swift
  DailyQuest/DailyQuest/Presentation/Home/Flow/HomeCoordinator.swift
  DailyQuest/DailyQuest/Presentation/Home/View/DayNamePickerView.swift
  DailyQuest/DailyQuest/Presentation/Home/View/PlanDatePickerView.swift
  DailyQuest/DailyQuest/Presentation/Home/View/QuantityView.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewController/EnrollViewController.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewModel/EnrollViewModel.swift
Labels: 리뷰요청, 진웅, feature

#84 Refactor/quests repository (1)
  DailyQuest/DailyQuest.xcodeproj/project.pbxproj
  DailyQuest/DailyQuest/Data/DataConfigure.swift
  DailyQuest/DailyQuest/Data/Network/DataMapping/QuestDTO+Mapping.swift
  DailyQuest/DailyQuest/Data/Repositories/DefaultQuestsRepository.swift
  DailyQuest/DailyQuest/Infrastructure/FirebaseService/FirebaseService.swift
  DailyQuest/DailyQuest/Infrastructure/NetworkConfigure.swift
  DailyQuest/DailyQuest/Infrastructure/NetworkService.swift
Labels: 리뷰요청, 전희, feature

#87 Feature/friend view
  DailyQuest/DailyQuest.xcodeproj/project.pbxproj
  DailyQuest/DailyQuest/Presentation/Common/FriendStatusView.swift
  DailyQuest/DailyQuest/Presentation/Common/ViewController/FriendViewController.swift
Labels: 리뷰요청, 진웅, feature

#90 Feature/enroll notify
  DailyQuest/DailyQuest.xcodeproj/project.pbxproj
  DailyQuest/DailyQuest/Domain/UseCases/Home/DefaultEnrollUseCase.swift
  DailyQuest/DailyQuest/Presentation/Home/Flow/HomeCoordinator.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewController/EnrollViewController.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewModel/EnrollViewModel.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewModel/QuestViewModel.swift
  DailyQuest/DailyQuest/Utils/Notification+.swift
Labels: 리뷰요청, 진웅, feature

#92 Refactor/browse view
  DailyQuest/DailyQuest/Assets.xcassets/ColorSet/MaxLightBlue.colorset/Contents.json
  DailyQuest/DailyQuest/Presentation/Browse/View/BrowseCell.swift
  DailyQuest/DailyQuest/Presentation/Browse/View/UserInfoView.swift
  DailyQuest/DailyQuest/Presentation/Common/Cells/QuestCell.swift
  DailyQuest/DailyQuest/Utils/UIColor+.swift
Labels: 진웅, refactor

#95 Fix/quest repository
  DailyQuest/DailyQuest.xcodeproj/project.pbxproj
  DailyQuest/DailyQuest/Data/PersistentStorages/RealmStorage/RealmStorage.swift
  DailyQuest/DailyQuest/Data/Repositories/DefaultBrowseRepository.swift
  DailyQuest/DailyQuest/Data/Repositories/DefaultQuestsRepository.swift
  DailyQuest/DailyQuest/Data/Repositories/DefaultUserRepository.swift
  DailyQuest/DailyQuest/Domain/Entities/User.swift
Labels: bug, 리뷰요청, 전희

#100 Refactor/home view
  DailyQuest/DailyQuest.xcodeproj/project.pbxproj
  DailyQuest/DailyQuest/Application/AppAppearance.swift
  DailyQuest/DailyQuest/Application/DIContainer/HomeSceneDIContainer.swift
  DailyQuest/DailyQuest/Data/Repositories/DefaultQuestsRepository.swift
  DailyQuest/DailyQuest/Presentation/Home/Flow/HomeCoordinator.swift
  DailyQuest/DailyQuest/Presentation/Home/View/QuestView.swift
  DailyQuest/DailyQuest/Presentation/Home/View/StatusView.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewController/HomeViewController.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewModel/HomeViewModel.swift
  DailyQuest/DailyQuest/Presentation/Settings/Flow/SettingsCoordinator.swift
  DailyQuest/DailyQuest/Presentation/Settings/ViewModel/LoginViewModel.swift
  DailyQuest/DailyQuest/Presentation/Settings/ViewModel/SignUpViewModel.swift
Labels: 진웅

#102 Refactor/user use case
  DailyQuest/DailyQuest.xcodeproj/project.pbxproj
  DailyQuest/DailyQuest/Application/DIContainer/HomeSceneDIContainer.swift
  DailyQuest/DailyQuest/Assets.xcassets/defaultBackground.imageset/Contents.json
  DailyQuest/DailyQuest/Assets.xcassets/defaultBackground.imageset/블러.png
  DailyQuest/DailyQuest/Data/Network/DataMapping/UserDTO+Mapping.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/BrowseQuestsStorage/RealmStorage/EntityMapping/BrowseQuestEntity+Mapping.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/RealmStorage/Entities/UserInfoEntity.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/RealmStorage/RealmStorage.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/UserInfoStorage/RealmStorage/EntityMapping/UserInfoEntity+Mapping.swift
  DailyQuest/DailyQuest/Data/Repositories/DefaultUserRepository.swift
  DailyQuest/DailyQuest/Domain/Entities/User.swift
  DailyQuest/DailyQuest/Domain/Interfaces/Repositories/UserRepository.swift
  DailyQuest/DailyQuest/Domain/UseCases/Browse/DefaultBrowseUseCase.swift
  DailyQuest/DailyQuest/Domain/UseCases/Home/DefaultUserUseCase.swift
  DailyQuest/DailyQuest/Domain/UseCases/Home/Protocols/UserUseCase.swift
  DailyQuest/DailyQuest/Infrastructure/FirebaseService/FirebaseService.swift
  DailyQuest/DailyQuest/Infrastructure/NetworkService.swift
  DailyQuest/DailyQuest/Presentation/Common/FriendStatusView.swift
  DailyQuest/DailyQuest/Presentation/Home/Flow/HomeCoordinator.swift
  DailyQuest/DailyQuest/Presentation/Home/View/StatusView.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewController/HomeViewController.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewController/ProfileViewController.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewModel/ProfileViewModel.swift
  DailyQuest/DailyQuest/Utils/UIImageView+.swift
  DailyQuest/DailyQuestTests/Mocks/User+Stub.swift
Labels: bug, 리뷰요청, 전희

#105 Feature/sign in sign up action
  DailyQuest/DailyQuest.xcodeproj/project.pbxproj
  DailyQuest/DailyQuest/Infrastructure/FirebaseService/FirebaseService.swift
  DailyQuest/DailyQuest/Presentation/Settings/Flow/SettingsCoordinator.swift
  DailyQuest/DailyQuest/Presentation/Settings/ViewController/LoginViewController.swift
  DailyQuest/DailyQuest/Presentation/Settings/ViewController/SignUpViewController.swift
  DailyQuest/DailyQuest/Utils/Alertable.swift
Labels: 진웅, feature

#109 Feature/quest view empty space
  DailyQuest/DailyQuest/Assets.xcassets/NoMoreQuests.imageset/Contents.json
  DailyQuest/DailyQuest/Assets.xcassets/NoMoreQuests.imageset/NoMoreQuests.png
  DailyQuest/DailyQuest/Presentation/Home/ViewController/HomeViewController.swift
Labels: 진웅, feature

#115 Feature/home view
  DailyQuest/DailyQuest/Application/DIContainer/HomeSceneDIContainer.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/QuestsStorage/RealmStorage/RealmQuestsStorage.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/UserInfoStorage/RealmStorage/RealmUserInfoStorage.swift
  DailyQuest/DailyQuest/Data/Repositories/DefaultAuthRepository.swift
  DailyQuest/DailyQuest/Domain/UseCases/Home/DefaultUserUseCase.swift
  DailyQuest/DailyQuest/Domain/UseCases/Settings/DefaultAuthUseCase.swift
  DailyQuest/DailyQuest/Presentation/Home/View/MessageBubble.swift
  DailyQuest/DailyQuest/Presentation/Home/View/StatusView.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewController/HomeViewController.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewController/ProfileViewController.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewModel/HomeViewModel.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewModel/ProfileViewModel.swift
Labels: 리뷰요청, 전희, refactor, feature

#120 Feature/profile view
  DailyQuest/DailyQuest.xcodeproj/project.pbxproj
  DailyQuest/DailyQuest.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DailyQuest/DailyQuest/Presentation/Home/View/CameraIconView.swift
  DailyQuest/DailyQuest/Presentation/Home/View/UserImageView.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewController/ProfileViewController.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewModel/ProfileViewModel.swift
Labels: 리뷰요청, 다연, feature

#122 Refactor/quest view header label
  DailyQuest/DailyQuest/Presentation/Home/View/QuestViewHeader.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewController/HomeViewController.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewModel/HomeViewModel.swift
Labels: 리뷰요청, 진웅, refactor

#124 Feature/friend view
  DailyQuest/DailyQuest.xcodeproj/project.pbxproj
  DailyQuest/DailyQuest/Application/DIContainer/BrowseSceneDIContainer.swift
  DailyQuest/DailyQuest/Domain/UseCases/Common/DefaultFriendCalendarUseCase.swift
  DailyQuest/DailyQuest/Domain/UseCases/Common/DefaultFriendQuestUseCase.swift
  DailyQuest/DailyQuest/Domain/UseCases/Common/Protocols/FriendCalendarUseCase.swift
  DailyQuest/DailyQuest/Domain/UseCases/Common/Protocols/FriendQuestUseCase.swift
  DailyQuest/DailyQuest/Presentation/Browse/Flow/BrowseCoordinator.swift
  DailyQuest/DailyQuest/Presentation/Browse/ViewController/BrowseViewController.swift
  DailyQuest/DailyQuest/Presentation/Common/FriendStatusView.swift
  DailyQuest/DailyQuest/Presentation/Common/ViewController/FriendViewController.swift
  DailyQuest/DailyQuest/Presentation/Common/ViewModel/FriendViewModel.swift
  DailyQuest/DailyQuest/Presentation/Home/View/QuestViewHeader.swift
Labels: 리뷰요청, 진웅, feature

#141 Refactor/browse view
  DailyQuest/DailyQuest/Domain/Entities/User.swift
  DailyQuest/DailyQuest/Domain/UseCases/Settings/DefaultSettingsUseCase.swift
  DailyQuest/DailyQuest/Domain/UseCases/Settings/Protocols/SettingsUseCase.swift
  DailyQuest/DailyQuest/Presentation/Browse/Flow/BrowseCoordinator.swift
  DailyQuest/DailyQuest/Presentation/Browse/View/UserInfoView.swift
  DailyQuest/DailyQuest/Presentation/Browse/ViewController/BrowseViewController.swift
  DailyQuest/DailyQuest/Presentation/Common/View/QuestViewHeader.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewModel/HomeViewModel.swift
  DailyQuest/DailyQuest/Presentation/Settings/View/ToggleField/ToggleCell.swift
  DailyQuest/DailyQuest/Presentation/Settings/View/ToggleField/ToggleItemViewModel.swift
  DailyQuest/DailyQuest/Presentation/Settings/ViewController/LoginViewController.swift
  DailyQuest/DailyQuest/Presentation/Settings/ViewController/SettingsViewController.swift
  DailyQuest/DailyQuest/Presentation/Settings/ViewController/SignUpViewController.swift
  DailyQuest/DailyQuest/Presentation/Settings/ViewModel/SettingsViewModel.swift
  DailyQuest/DailyQuest/Utils/Date+.swift
Labels: 전희, refactor

#149 Refactor/friend view calendar fetch
  DailyQuest/DailyQuest.xcodeproj/project.pbxproj
  DailyQuest/DailyQuest/Application/DIContainer/BrowseSceneDIContainer.swift
  DailyQuest/DailyQuest/Data/Repositories/DefaultQuestsRepository.swift
  DailyQuest/DailyQuest/Domain/Interfaces/Repositories/QuestsRepository.swift
  DailyQuest/DailyQuest/Domain/UseCases/Common/DefaultFriendCalendarUseCase.swift
  DailyQuest/DailyQuest/Domain/UseCases/Common/Protocols/FriendCalendarUseCase.swift
  DailyQuest/DailyQuest/Presentation/Common/ViewController/FriendViewController.swift
  DailyQuest/DailyQuest/Presentation/Common/ViewModel/FriendViewModel.swift
Labels: 동훈, refactor

#150 Refactor/di container
  DailyQuest/DailyQuest.xcodeproj/project.pbxproj
  DailyQuest/DailyQuest/Application/Container/Repository/RepositoryKey.swift
  DailyQuest/DailyQuest/Application/Container/Service/ServiceKey.swift
  DailyQuest/DailyQuest/Application/Container/Storage/StroageKey.swift
  DailyQuest/DailyQuest/Application/Container/UseCase/UseCaseKey.swift
  DailyQuest/DailyQuest/Application/DIContainer/AppDIContainer.swift
  DailyQuest/DailyQuest/Application/DIContainer/HomeSceneDIContainer.swift
  DailyQuest/SubFrameworks/DailyContainer/DailyContainer.xcodeproj/project.pbxproj
  DailyQuest/SubFrameworks/DailyContainer/DailyContainer.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  DailyQuest/SubFrameworks/DailyContainer/DailyContainer.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  DailyQuest/SubFrameworks/DailyContainer/DailyContainer/Container.swift
  DailyQuest/SubFrameworks/DailyContainer/DailyContainer/DailyContainer.docc/DailyContainer.md
  DailyQuest/SubFrameworks/DailyContainer/DailyContainer/DailyContainer.h
  DailyQuest/SubFrameworks/DailyContainer/DailyContainer/Injected.swift
  DailyQuest/SubFrameworks/DailyContainer/DailyContainer/InjectionKey.swift
Labels: 리뷰요청, 진웅, refactor

#151 Feature/launch view
  DailyQuest/DailyQuest.xcodeproj/project.pbxproj
  DailyQuest/DailyQuest/Application/SceneDelegate.swift
  DailyQuest/DailyQuest/Presentation/Common/ViewController/LaunchViewController.swift
  DailyQuest/DailyQuest/Resource/max.lottie.json
Labels: 다연, feature

#152 Feature/profile view
  DailyQuest/DailyQuest.xcodeproj/project.pbxproj
  DailyQuest/DailyQuest.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  DailyQuest/DailyQuest/Application/SyncManager.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/BrowseQuestsStorage/RealmStorage/RealmBrowseQuestsStorage.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/QuestsStorage/RealmStorage/RealmQuestsStorage.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/RealmStorage/RealmStorage.swift
  DailyQuest/DailyQuest/Data/PersistentStorages/UserInfoStorage/RealmStorage/RealmUserInfoStorage.swift
  DailyQuest/DailyQuest/Data/Repositories/DefaultBrowseRepository.swift
  DailyQuest/DailyQuest/Domain/Entities/User.swift
  DailyQuest/DailyQuest/Domain/UseCases/Home/DefaultUserUseCase.swift
  DailyQuest/DailyQuest/Domain/UseCases/Home/Protocols/UserUseCase.swift
  DailyQuest/DailyQuest/Infrastructure/FirebaseService/FirebaseService.swift
  DailyQuest/DailyQuest/Presentation/Common/View/FriendStatusView.swift
  DailyQuest/DailyQuest/Presentation/Home/View/CameraIconView.swift
  DailyQuest/DailyQuest/Presentation/Home/View/UserImageView.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewController/ProfileViewController.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewModel/ProfileViewModel.swift
Labels: 다연, feature

#154 Refactor/calendar view scroll bug fix
  DailyQuest/DailyQuest/Presentation/Common/CalendarView.swift
  DailyQuest/DailyQuest/Presentation/Common/ViewController/FriendViewController.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewController/HomeViewController.swift
Labels: 동훈, refactor

#156 Refactor/scene di container
  DailyQuest/DailyQuest/Application/Container/UseCase/UseCaseKey.swift
  DailyQuest/DailyQuest/Application/DIContainer/BrowseSceneDIContainer.swift
  DailyQuest/DailyQuest/Application/DIContainer/HomeSceneDIContainer.swift
  DailyQuest/DailyQuest/Application/DIContainer/SettingsSceneDIContainer.swift
Labels: 진웅, refactor

#158 Refactor/calendar view selected date bug fix
  DailyQuest/DailyQuest/Domain/Entities/DailyQuestCompletion.swift
  DailyQuest/DailyQuest/Domain/UseCases/Common/DefaultFriendCalendarUseCase.swift
  DailyQuest/DailyQuest/Domain/UseCases/Home/HomeCalendarUseCase.swift
  DailyQuest/DailyQuest/Domain/UseCases/Home/Protocols/CalendarUseCase.swift
  DailyQuest/DailyQuest/Presentation/Common/CalendarView.swift
  DailyQuest/DailyQuest/Presentation/Common/ViewController/FriendViewController.swift
  DailyQuest/DailyQuest/Presentation/Common/ViewModel/FriendViewModel.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewController/HomeViewController.swift
  DailyQuest/DailyQuest/Presentation/Home/ViewModel/HomeViewModel.swift
Labels: bug, 동훈, refactor
